# -- Setup -- #

# Remap prefix from <ctrl-b> to <ctlr-a>
unbind C-b
set-option -g prefix C-a
bind-key C-a send prefix

# Split panes with | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Source config
bind r source-file ~/.tmux.conf

# Switch panes using meta(alt in this case)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse
set -g mouse on

# Use all colors
set-option -g default-terminal "screen-256color"  # use 256 colors

# More history buffer
set-option -g history-limit 100000

# Make it more responsive
set-option -g repeat-time 0       

# DESIGN
